apiVersion: apps.kubeblocks.io/v1alpha1
kind: BackupPolicyTemplate
metadata:
  name: apecloud-mysql-backup-policy-template
  labels:
    clusterdefinition.kubeblocks.io/name: apecloud-mysql
    {{- include "apecloud-mysql.labels" . | nindent 4 }}
  annotations:
    dataprotection.kubeblocks.io/is-default-policy-template: "true"
spec:
  clusterDefinitionRef: apecloud-mysql
  backupPolicies:
  - componentDefRef: mysql
    target:
      role: leader
    backupMethods:
    - name: xtrabackup
      snapshotVolumes: false
      actionSetName: xtrabackup-for-apecloud-mysql
      targetVolumes:
        volumeMounts:
        - name: data
          mountPath: {{ .Values.mysqlConfigs.dataMountPath }}
    - name: volume-snapshot
      snapshotVolumes: true
      actionSetName: volumesnapshot-for-apecloud-mysql
      targetVolumes:
        volumes:
        - data
        volumeMounts:
        - name: data
          mountPath: {{ .Values.mysqlConfigs.dataMountPath }}
    schedules:
    - backupMethod: xtrabackup
      retentionPeriod: 7d
      enabled: false
      cronExpression: "0 18 * * *"
    - backupMethod: volume-snapshot
      retentionPeriod: 7d
      enabled: false
      cronExpression: "0 18 * * *"