annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 3.3.2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Kafka is a distributed streaming platform designed to build real-time
  pipelines and can be used as a message  broker or as a replacement for a log aggregation
  solution for big data applications. This chart provides KubeBlocks' ClusterDefinition
  API manifests.
home: https://kubeblocks.io/
icon: https://kubeblocks.io/img/logo.png
keywords:
- kafka
- kraft
- streaming
- producer
- consumer
maintainers:
- name: Nash Tsai
  url: https://github.com/apecloud/kubeblocks/deploy
name: kafka
type: application
version: 0.7.1
